const targets = {
  1: [
    'CeeDee Lamb',
    'Brian Thomas Jr.',
    'Nico Collins',
  ],
  2: [
    'Bucky Irving',
    'Josh Jacobs',
    'Jonathan Taylor',
    'Chase Brown',
    'Kyren Williams',
    'Brock Bowers',
    'Trey McBride',
  ],
  3: [
    'Josh Allen',
    'Lamar Jackson',
    'Jayden Daniels',
    'George Kittle',
    'Omarion Hampton',
  ],
  4: [
    'Jalen Hurts',
    'Joe Burrow',
    'Chuba Hubbard',
    'Kenneth Walker III',
    'James Conner',
  ],
  5: [
    'Calvin Ridley',
    'Courtland Sutton',
    'Zay Flowers',
    'Jerry Jeudy',
    'Tetairoa McMillan',
    'DK Metcalf',
    'Stefon Diggs',
    'Khalil Shakir',
    'Josh Downs',
    'DeVonta Smith',
    'Jameson Williams',
    'Rome Odunze',
    'Travis Hunter',
    'George Pickens',
    'Jaylen Waddle',
    'Ricky Pearsall',
  ],
  6: [
    'David Montgomery',
    'Tony Pollard',
    'RJ Harvey',
    'Kaleb Johnson',
    'Isiah Pacheco',
  ],
  7: [
    'Jakobi Meyers',
    'D\'Andre Swift',
    'TreVeyon Henderson'
  ],
  8: [
    'Jayden Reed',
    'Matthew Golden',
    'Tyler Warren',
  ],
  9: [
    'Justin Fields',
    'Tucker Kraft',
    'Keon Coleman',
  ],
  10: [
    'Tank Bigsby',
    'Jordan Love',
    'Justin Herbert',
    'Brock Purdy',
    'Dak Prescott',
    'Caleb Williams',
    'Drake Maye',
    'C.J. Stroud',
    'J.J. McCarthy',
    'Tyjae Spears',
    'Zach Charbonnet',
    'Rachaad White',
    'Trey Benson',
    'Isaac Guerendo',
    'Jaylen Wright',
    'Tyler Allgeier',
    'Rhamondre Stevenson',
    'Rico Dowdle',
    'Ray Davis',
  ],
  11: [
    'Dallas Goedert',
    'Rashid Shaheed',
    'Cedric Tillman',
    'Marvin Mims',
    'Braelon Allen',
    'Jaydon Blue',
    'Jalen Coker',
  ],
  12: [
    'Hunter Henry'
  ],
  13: [
    'Theo Johnson'
  ],
};

export default targets;
