const targets = {
  1: [
    'Christian McCaffrey',
    'Breece Hall',
    'Bijan Robinson',
    'Best Available WR',
  ],
  2: [
    'Derrick Henry',
    'Kyren Williams',
    'Isiah Pacheco',
    'Garrett Wilson',
    'Marvin Harrison Jr.',
  ],
  3: [
    'Mike Evans',
    'Deebo Samuel Sr.',
    'Brandon Aiyuk',
    'Cooper Kupp',
    'DK Metcalf',
    'Devonta Smith',
    'Sam LaPorta',
    'Jalen Hurts',
    'Josh Allen',
    'Patrick Mahomes',
  ],
  4: [
    'Mark Andrews',
    'Kenneth Walker III',
    'Alvin Kamara',
    'Lamar Jackson',
  ],
  5: [
    'James Conner',
    'David Montgomery',
    'Aaron Jones',
    'Amari Cooper',
    'Tank Dell',
    'George Pickens',
    'Rashee Rice',
    'Dalton Kincaid',
    'Kyle Pitts',
    'George Kittle',
  ],
  6: [
    'Terry McLaurin',
    'Christian Kirk',
    'Keenan Allen',
    'Calvin Ridley',
    'Kyler Murray',
  ],
  7: [
    'Chris Godwin',
    'Diontae Johnson',
    'Raheem Mostert',
    'Najee Harris',
    'Jonathon Brooks',
    'Jake Ferguson',
    'Jayden Daniels',
  ],
  8: [
    'Xavier Worthy',
    'Christian Watson',
    'Jaxon Smith-Njigba',
    'Rome Odunze',
  ],
  9: [
    'Brian Thomas Jr.',
    'Ladd McConkey',
    'Courtland Sutton',
    'Deandre Hopkins',
  ],
  10: [
    'Nick Chubb',
    'Chase Brown', 
    'Blake Corum',
    'Jared Goff',
    'Tua Tagovailoa', 
    'Trevor Lawrence', 
    'Caleb Williams',
    'Dallas Goedert',
  ],
  11: [
    'Joshua Palmer',
    'Curtis Samuel',
    'Brandin Cooks',
    'Rashid Shaheed',
    'Trey Benson',
    'Zach Charbonnet',
    'J.K. Dobbins',
    'Rico Dowdle',
    'Chuba Hubbard',
    'Tyler Allgeier',
    'Ty Chandler',
    'Jaylen Wright',
    'Justin Herbert', 
    'Kirk Cousins',
    'Aaron Rodgers', 
    'Matthew Stafford',
  ],
};

export default targets;
